name : Deploy to GCP App Engine 

# Triggers 
on: 
  push : 
    branches : [main]
  pull_request : 
    branches : [main]
    
# Jobs 
jobs:
  deploy : 
    name: Deploying to GCP Project 
    runs-on : ubuntu-latest
  
    steps:
    - name: checkout
      uses : actions/checkout@v2
      
    - name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.CREDENTIALS }}'

    - name : GCP deploy 
      uses : google-github-actions/deploy-appengine@v0.2.0
      with : 
        deliverables : app.yaml
        project_id : ${{ secrets.PROJECT_ID }}
        credentials : ${{ secrets.CREDENTIALS }}

    - name : Test deployment 
      run : curl "https://mr-buy-370317.as.r.appspot.com/"
